[work]
name = 'FT-2_LH' # name of calculation
description = 'test FT-2 LH'

[series]
number = 2
var = 'Nr'
var_type = 'int'
start = 101 
step = 10

[params]
field_solver_ver = 2 # 0 old, 1 MKL+OMP, 2 (MKL+OMP+no_inv_mat)

[w2grid]
# comments
Nr = 601	  # number of radial points
nphi1 = -122	  # integer start toroidal wavenumber (Ntor1 = nphi1/R)
nphi2 = -122	  # integer final toroidal wavenumber (Ntor2 = nphi2/R)
nphistep = 1      # integer step for toroidal mode number
Mmax = 180        # maximum poloidal mode number
Mspow_excess = 1  # Mspow_excess (non-negative): Msmax = Msmax_min_permissible * 2**Mspow_excess
Pinterv = 0  # number of traced time intervals

[w2source]
# comments
AntType = 1	    # 0-Sngl.Mode, 1-Grill, 2-Strap, 3-Spher.Front, 4-Gaus.Beam, 5-File, 6-BasicSet, 7-Imped
Pinp = 200.0	# Pinp(kW)

[w2strap]
faraday_screen  = false # logical - if Faraday screen is present
strap_distance  = 2.0    # strap distance from the wall (cm)
screen_distance = 3.0    # screen distance from the wall (cm)
strap_angle = 0.0        # strap inclination angle to the poloidal direction (degrees)
poloidal_position = 0.0  # strap center poloidal position (theta, degrees)
poloidal_height = 60.0   # strap poloidal height (theta, degrees)
strap_current = 1.0      # strap current